In [1]:
from __future__ import print_function
import torch
import numpy as np


# 1. 张量（Tensor)
tensor于numpy的ndarrays，不同之处在于tensor可以使用GPU来加快计算。

## 1.1 创建一个未初始化的5*3的矩阵：

In [46]:
x = torch.Tensor(5, 3)
print(x)
print('x.dtype=',x.dtype)

tensor([[ 0.0000e+00,  0.0000e+00,  1.2163e-42],
        [ 0.0000e+00,  7.0065e-45,  0.0000e+00],
        [-2.6090e+09,  5.0587e-43,  0.0000e+00],
        [ 0.0000e+00,  7.0065e-45,  0.0000e+00],
        [-3.0255e+09,  5.0587e-43,  0.0000e+00]])
x.dtype= torch.float32


## 1.2 获取tensor的属性（形状大小、维度个数、数据类型、元素个数）

In [50]:
# 获取形状大小的两种方法：
print('法①：x.size()=',x.size())
print('torch.Size()返回的实际上是一个元组，所以它支持元组的所有操作。')
print('法②：x.shape=',x.shape)
print()

# 获取维度个数
print('x.dim()=',x.dim())
print()

# 获取数据类型
print('x.dtype=',x.dtype)
print()

# 获取元素个数
print('x.numel()=',x.numel())

法①：x.size()= torch.Size([5, 3])
torch.Size()返回的实际上是一个元组，所以它支持元组的所有操作。
法②：x.shape= torch.Size([5, 3])

x.dim()= 2

x.dtype= torch.float32

x.numel()= 15


## 1.3 构建一个初始化矩阵
- 0初始化，使用long的类型  
- 1初始化
- 随机[0, 1)初始化
- 等差数列初始化 
- 标准正态分布初始化
- eye初始化

In [82]:
x = torch.zeros(5, 3, dtype=torch.long)
# 1初始化
# x = torch.ones(5, 3, dtype=torch.long)

# [0,1)初始化
# x = torch.rand(5,3)

# 等差数列初始化 
x = torch.arange(10,20,2)

# 标准正态分布初始化
# x =torch.randn(5,3)

# eye初始化：para1决定张量的形状，比如3，就是三行三列，para2决定张量输出的列数，比如2，输出列数则为2。
# x=torch.eye(5,3)
print(x)

tensor([10, 12, 14, 16, 18])


## 1.4 从数据中直接构建一个tensor：

In [4]:
x = torch.tensor([5.5, 3])
print(x,x.dtype)

tensor([5.5000, 3.0000]) torch.float32


## 1.5 根据已有的tensor建立新的tensor:
除非用户提供新值,这些方法将重用输入张量(tensor)的属性，例如dtype

In [11]:
x = x.new_zeros(5, 3, dtype=torch.double)     # 打印：tensor([[0,0,0],[0,0,0],...])
print(x)
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float)    # 覆盖类型! result 的size相同，数据变为随机值。
print(x)                                   

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float64)
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 0.7542, -0.1806, -0.7456],
        [-0.3787,  1.2365,  1.0395],
        [ 0.8733, -2.2402, -0.8755],
        [ 0.9496,  1.5125,  0.0083],
        [-0.5588, -0.5435,  0.0065]])


# 2. tensor上的运算

一种运算有多种语法。在下面的示例中，我们将研究加法运算。
   ## 2.1 加法的3种形式

In [23]:
# 加法的2种形式
# 法①
y = torch.rand(5, 3)
c=x + y
print(c)

# 法②
print(torch.add(x, y))

# 法③
result = torch.empty(5, 2)
#print(result)
torch.add(x,y,out=result)
print(result)

tensor([[ 1.6529,  0.4947,  0.2033],
        [ 0.5041,  1.5942,  1.9702],
        [ 1.5319, -1.7636,  0.0310],
        [ 1.6111,  1.5339,  0.7098],
        [ 0.4113, -0.5045,  0.7432]])
tensor([[ 1.6529,  0.4947,  0.2033],
        [ 0.5041,  1.5942,  1.9702],
        [ 1.5319, -1.7636,  0.0310],
        [ 1.6111,  1.5339,  0.7098],
        [ 0.4113, -0.5045,  0.7432]])
tensor([[ 1.6529,  0.4947,  0.2033],
        [ 0.5041,  1.5942,  1.9702],
        [ 1.5319, -1.7636,  0.0310],
        [ 1.6111,  1.5339,  0.7098],
        [ 0.4113, -0.5045,  0.7432]])


## 2.2 原地操作（in-place）
>注意：
>任何一个改变张量的操作后面都固定一个\_。例如x.copy\_(y)、x.t\_()将更改x

In [24]:
# 把x加到y上
y.add_(x)
print(y)

tensor([[ 1.6529,  0.4947,  0.2033],
        [ 0.5041,  1.5942,  1.9702],
        [ 1.5319, -1.7636,  0.0310],
        [ 1.6111,  1.5339,  0.7098],
        [ 0.4113, -0.5045,  0.7432]])


## 2.3 可以使用像标准的NumPy一样的各种索引操作

In [25]:
print(x)
print(x[:, 1])

tensor([[ 0.7542, -0.1806, -0.7456],
        [-0.3787,  1.2365,  1.0395],
        [ 0.8733, -2.2402, -0.8755],
        [ 0.9496,  1.5125,  0.0083],
        [-0.5588, -0.5435,  0.0065]])
tensor([-0.1806,  1.2365, -2.2402,  1.5125, -0.5435])


## 2.4 改变形状
如果想改变形状，可以使用torch.view,还可以使用unsqueeze()函数增加维度。

In [28]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # -1的意思是没有指定维度
print(x.size(), y.size(), z.size())
print(x)
print(y)

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])
tensor([[ 1.1834, -0.4473, -1.4750, -1.4320],
        [ 0.1730,  0.0911, -1.2494,  1.0530],
        [ 0.6912,  1.1631, -1.0222,  1.0408],
        [ 0.1931, -1.0624, -1.0157,  0.4932]])
tensor([ 1.1834, -0.4473, -1.4750, -1.4320,  0.1730,  0.0911, -1.2494,  1.0530,
         0.6912,  1.1631, -1.0222,  1.0408,  0.1931, -1.0624, -1.0157,  0.4932])


In [6]:
a = torch.arange(5)
print(a)
b=a.unsqueeze(1)
print(b)
c= b.unsqueeze(1)
print(c)

tensor([0, 1, 2, 3, 4])
tensor([[0],
        [1],
        [2],
        [3],
        [4]])
tensor([[[0]],

        [[1]],

        [[2]],

        [[3]],

        [[4]]])


## 2.5 如果是仅包含一个元素的tensor，可以使用.item()来得到对应的python数值

In [29]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([-2.8661])
-2.866062879562378


## 2.6 稍后阅读
[这里](https://pytorch.org/docs/stable/torch.html)描述了一百多种张量操作，包括转置，索引，数学运算，线性代数，随机数等。

## 2.7 torch中的数学运算

In [6]:
# abs 绝对值计算
data = [-1, -2, 1, 2]
print(type(data))
tensor = torch.FloatTensor(data)  # 转换成32位浮点 tensor
print(
    '\nabs',
    '\nnumpy: ', np.abs(data),          # [1 2 1 2]
    '\ntorch: ', torch.abs(tensor),tensor.dtype      # [1 2 1 2]
)

# sin   三角函数 sin
print(
    '\nsin',
    '\nnumpy: ', np.sin(data),      # [-0.84147098 -0.90929743  0.84147098  0.90929743]
    '\ntorch: ', torch.sin(tensor)  # [-0.8415 -0.9093  0.8415  0.9093]
)

# mean  均值
print(
    '\nmean',
    '\nnumpy: ', np.mean(data),         # 0.0
    '\ntorch: ', torch.mean(tensor)     # 0.0
)

<class 'list'>

abs 
numpy:  [1 2 1 2] 
torch:  tensor([1., 2., 1., 2.]) torch.float32

sin 
numpy:  [-0.84147098 -0.90929743  0.84147098  0.90929743] 
torch:  tensor([-0.8415, -0.9093,  0.8415,  0.9093])

mean 
numpy:  0.0 
torch:  tensor(0.)


matrix multiplication 矩阵点乘

In [28]:
data = [[1,2], [3,4]]
print(type(data))
tensor = torch.FloatTensor(data)  # 转换成32位浮点 tensor
# correct method
print(
    '\nmatrix multiplication (matmul)',
    '\nnumpy: ', np.matmul(data, data),     # [[7, 10], [15, 22]]
    '\ntorch: ', torch.mm(tensor, tensor)   # [[7, 10], [15, 22]]
)

data = np.array(data)
print(type(data))

<class 'list'>

matrix multiplication (matmul) 
numpy:  [[ 7 10]
 [15 22]] 
torch:  tensor([[ 7., 10.],
        [15., 22.]])
<class 'numpy.ndarray'>


# 3. NumPy桥
把一个torch张量转换为numpy数组或者反过来都是很简单的。  
Torch张量和NumPy数组将共享它们的底层内存位置，更改一个将更改另一个。


## 3.1 把Torch张量转换为numpy数组
二者共享内存

In [36]:
a = torch.ones(5)
print(a,a.dtype)
print(type(a))
print()

# 把Torch张量a转换为numpy数组b
b = a.numpy()
print(b,b.dtype)
print(type(b))

tensor([1., 1., 1., 1., 1.]) torch.float32
<class 'torch.Tensor'>

[1. 1. 1. 1. 1.] float32
<class 'numpy.ndarray'>


In [37]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


## 3.2 把numpy数组转换为torch张量
二者共享内存

In [39]:
a = np.ones(5)
print(a)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[1. 1. 1. 1. 1.]
[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


## 3.3 CUDA张量
可以使用.to方法将张量移动到任何设备上。

In [44]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!

# 4. ~~variable~~
在 Torch 中的 Variable 就是一个存放会变化的值的变量，里面的值会不停的变化。  
  
  
**PyTorch0.4后Tensor和Variable合并**，torch.Tensor 和torch.autograd.Variable现在是同一个类。torch.Tensor 能够像之前的Variable一样追踪历史和反向传播。

In [66]:
from torch.autograd import Variable
tensor=torch.FloatTensor([[1,2],[3,4]])
variable=Variable(tensor,requires_grad=True)
print(tensor*tensor)

t_out=torch.mean(tensor*tensor)
v_out=torch.mean(variable*variable)
print(t_out)
print(v_out)

tensor([[ 1.,  4.],
        [ 9., 16.]])
tensor(7.5000)
tensor(7.5000, grad_fn=<MeanBackward1>)


## 4.1 variable 计算，梯度  
Variable 计算时, 它在背后一步步默默地搭建着计算图, computational graph. 这个图是用来干嘛的? 原来是将所有的计算步骤 (节点) 都连接起来, 最后进行误差反向传递的时候, 一次性将**所有 variable 里面的梯度**都计算出来, 而 tensor 就没有这个能力啦

In [67]:
v_out.backward()    # 模拟 v_out 的误差反向传递
print(variable.grad)    # 初始 Variable 的梯度

tensor([[0.5000, 1.0000],
        [1.5000, 2.0000]])


## 4.2 获取 Variable 里面的数据 

In [81]:
#variable形式
print(variable)
print(type(variable))
print()

# tensor形式
print(variable.data)
print(type(variable.data))
print()

#numpy形式
print(variable.detach().numpy())
print(type(variable.data.numpy()))

tensor([[1., 2.],
        [3., 4.]], requires_grad=True)
<class 'torch.Tensor'>

tensor([[1., 2.],
        [3., 4.]])
<class 'torch.Tensor'>

[[1. 2.]
 [3. 4.]]
<class 'numpy.ndarray'>


# Adaboost 算法介绍

## 1. Adaboost简介

### 1.1 集成学习（ensemble learning）背景介绍

集成学习（ensemble learning）通过构建并结合多个学习器（learner）来完成学习任务，通常可获得比单一学习器更良好的泛化性能（特别是在集成弱学习器[weak learner]时）。  

目前集成学习主要分为2大类：  

一类是以bagging、Random Forest等算法为代表的，**各个学习器之间相互独立、可同时生成**的并行化方法；

一类是以boosting、Adaboost等算法为代表的，**个体学习器是串行生成的、具有依赖关系的**序列化方法，它试图不断增强学习器的学习能力。

### 1.2 Adaboost背景介绍

Adaboost是Yoav Freund和Robert Schapire在1997年提出的一种集成学习（ensemble learning）算法。  

此前也Schapire也曾提出了一种boosting算法（Schapire’s Boosting ），但实际应用效果并不好，主要原因是因为Schapire’s Boosting 对于训练集样本的选取条件十分精确而又苛刻，以至于很难找出符合条件的训练集: (。而Adaboost在选取样本的时候采用了基于概率分布（也可解释为基于权值）来选取样本的方法，相比Schapire’s Boosting 放宽了对于训练样本选取的要求。  

## 2. Adaboost 算法详解

### 2.1 Adaboost 步骤概览

1. 初始化训练样本的权值分布，每个训练样本的权值应该相等（如果一共有N个样本，则每个样本的权值为1/N)
2. 依次构造训练集并训练弱分类器。如果一个样本被准确分类，那么它的权值在下一个训练集中就会降低；相反，如果它被分类错误，那么它在下个训练集中的权值就会提高。权值更新过后的训练集会用于训练下一个分类器。
3. 将训练好的弱分类器集成为一个强分类器，误差率小的弱分类器会在最终的强分类器里占据更大的权重，否则较小。  

### 2.2 Adaboost 算法流程

给定一个样本数量为m的数据集T=
$
\left(x_{1}, y_{1}\right), \ldots,\left(x_{m}, y_{m}\right)
$


























